#!/usr/bin/env python3
"""
bin2carray.py
-------------
Convert a binary file (e.g., an FPGA .bit bitstream) into a C header that
contains a byte array and a length constant.

Usage:
  python3 tools/bin2carray.py input.bin output.h symbol_name

Example:
  python3 tools/bin2carray.py build/soc_top.bit stm32/bitstream/ecp5_bitstream.h ecp5_bitstream
"""
from __future__ import annotations

import sys
from pathlib import Path

def main() -> int:
    if len(sys.argv) != 4:
        print("Usage: bin2carray.py <input.bin> <output.h> <symbol_name>", file=sys.stderr)
        return 2

    in_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    sym = sys.argv[3]

    data = in_path.read_bytes()

    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("/* Auto-generated by tools/bin2carray.py */")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"static const uint8_t {sym}[] = {{")

    # 12 bytes per line is a readable compromise
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    lines.append("};")
    lines.append(f"static const uint32_t {sym}_len = {len(data)}u;")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path} ({len(data)} bytes) as symbol '{sym}'")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
