#!/usr/bin/env python3
'''
Generate plaintext + encrypted Tetris GPU command ROMs.

This matches rtl/gpu/gpu_tetris_engine.sv and the AES bit ordering in
rtl/se/aes_enc_core.sv.

Output:
  - rtl/gpu/tetris_cmd_rom_plain.sv
  - rtl/gpu/tetris_cmd_rom_enc.sv
  - firmware/tetris_cmd_plain_128b.txt
  - firmware/tetris_cmd_enc_128b.txt
'''
from Crypto.Cipher import AES
from pathlib import Path

KEY_HEX = "000102030405060708090a0b0c0d0e0f"
SEED    = 0x1122334455667788

def pack_clear():
    return (0x01 << 56)

def pack_setcell(x, y, val):
    return (0x02<<56) | ((val & 0xF)<<52) | ((x & 0xF)<<48) | ((y & 0x1F)<<43)

def pack_wait(frames):
    return (0x03<<56) | (frames & 0xFFFF)

def pack_end():
    return (0xFF<<56)

def gen_cmds():
    cmds = []
    cmds.append(pack_clear())

    # bottom row
    for x in range(10):
        cmds.append(pack_setcell(x, 19, 8))

    # animate a vertical I piece falling at x=4
    frames_per_step = 4
    x_piece = 4
    for step in range(0, 16):
        if step > 0:
            for k in range(4):
                cmds.append(pack_setcell(x_piece, step-1+k, 0))
        for k in range(4):
            cmds.append(pack_setcell(x_piece, step+k, 1))
        cmds.append(pack_wait(frames_per_step))

    cmds.append(pack_end())
    return cmds

def aes_keystream_low64(key_bytes: bytes, seed_u64: int, ctr_u64: int) -> int:
    # Hardware uses AES_encrypt( {seed, ctr} ), treating the 128-bit block as bytes
    # where block_in[127:120] is byte0. That matches "big-endian" to_bytes here.
    block = seed_u64.to_bytes(8, "big") + ctr_u64.to_bytes(8, "big")
    out = AES.new(key_bytes, AES.MODE_ECB).encrypt(block)
    # Hardware uses block_out[63:0] => last 8 bytes of out
    return int.from_bytes(out[8:16], "big")

def gen_entries(cmds, encrypt: bool):
    key = bytes.fromhex(KEY_HEX)
    out = []
    for i, payload in enumerate(cmds):
        ctr = i + 1
        if encrypt:
            ks = aes_keystream_low64(key, SEED, ctr)
            data64 = payload ^ ks
        else:
            data64 = payload
        entry = (ctr << 64) | (data64 & ((1<<64)-1))
        out.append(entry)
    return out

def emit_rom_sv(mod_name: str, entries):
    lines = []
    lines.append("// -----------------------------------------------------------------------------")
    lines.append(f"// {mod_name}.sv")
    lines.append("// Autogenerated by tools/gen_tetris_rom.py")
    lines.append("// entry[127:64]=ctr, entry[63:0]=payload or enc_payload")
    lines.append("// -----------------------------------------------------------------------------")
    lines.append(f"module {mod_name}(")
    lines.append("    input  wire [7:0]  addr,")
    lines.append("    output logic [127:0] data")
    lines.append(");")
    lines.append("    always_comb begin")
    lines.append("        unique case (addr)")
    for i, val in enumerate(entries):
        lines.append(f"            8'd{i}: data = 128'h{val:032x};")
    lines.append("            default: data = 128'd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)

def main():
    root = Path(__file__).resolve().parents[1]
    rtl_gpu = root / "rtl" / "gpu"
    fw_dir  = root / "firmware"
    rtl_gpu.mkdir(parents=True, exist_ok=True)
    fw_dir.mkdir(parents=True, exist_ok=True)

    cmds = gen_cmds()
    plain = gen_entries(cmds, encrypt=False)
    enc   = gen_entries(cmds, encrypt=True)

    (rtl_gpu/"tetris_cmd_rom_plain.sv").write_text(emit_rom_sv("tetris_cmd_rom_plain", plain))
    (rtl_gpu/"tetris_cmd_rom_enc.sv").write_text(emit_rom_sv("tetris_cmd_rom_enc", enc))

    (fw_dir/"tetris_cmd_plain_128b.txt").write_text("\n".join(f"{v:032x}" for v in plain) + "\n")
    (fw_dir/"tetris_cmd_enc_128b.txt").write_text("\n".join(f"{v:032x}" for v in enc) + "\n")

    print("Generated:")
    print(" - rtl/gpu/tetris_cmd_rom_plain.sv")
    print(" - rtl/gpu/tetris_cmd_rom_enc.sv")
    print(" - firmware/tetris_cmd_plain_128b.txt")
    print(" - firmware/tetris_cmd_enc_128b.txt")

if __name__ == "__main__":
    main()
